2025-01-30 07:02:00,055 - __main__ - INFO - Starting Lazzaran Voice Assistant
2025-01-30 07:02:05,023 - __main__ - INFO - Starting voice recognition
2025-01-30 07:02:05,028 - __main__ - ERROR - Error in voice recognition loop: Could not find PyAudio; check installation
2025-01-30 07:02:07,032 - __main__ - INFO - Stopping voice recognition
2025-01-30 07:02:08,658 - __main__ - INFO - Cleaning up resources
2025-01-30 07:06:39,992 - __main__ - INFO - Starting Lazzaran Voice Assistant
2025-01-30 07:06:42,744 - __main__ - INFO - Starting voice recognition
2025-01-30 07:06:43,852 - core.voice_assistant - INFO - Recording...
2025-01-30 07:06:51,777 - core.voice_assistant - ERROR - Error in speech recognition: 
2025-01-30 07:06:51,790 - core.voice_assistant - INFO - Recording...
2025-01-30 07:06:59,398 - core.voice_assistant - INFO - Recognized text: Merhaba Ben Mert
2025-01-30 07:07:02,406 - google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
2025-01-30 07:07:06,411 - google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
2025-01-30 07:07:11,266 - google.auth.compute_engine._metadata - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
2025-01-30 07:07:11,266 - google.auth._default - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
2025-01-30 07:07:11,266 - core.services.ai_service - ERROR - Error getting AI response: 
  No API_KEY or ADC found. Please either:
    - Set the `GOOGLE_API_KEY` environment variable.
    - Manually pass the key with `genai.configure(api_key=my_api_key)`.
    - Or set up Application Default Credentials, see https://ai.google.dev/gemini-api/docs/oauth for more information.
2025-01-30 07:07:21,498 - core.voice_assistant - ERROR - Error cleaning up audio file: [WinError 32] Dosya baþka bir iþlem tarafýndan kullanýldýðýndan bu iþlem dosyaya eriþemiyor: 'C:\\Users\\MONSTER\\.lazzaran\\temp\\response.mp3'
2025-01-30 07:07:22,572 - core.voice_assistant - INFO - Recording...
2025-01-30 07:07:23,321 - __main__ - INFO - Stopping voice recognition
2025-01-30 07:07:26,450 - __main__ - INFO - Cleaning up resources
2025-01-30 07:07:26,452 - __main__ - ERROR - Cleanup error: [WinError 32] Dosya baþka bir iþlem tarafýndan kullanýldýðýndan bu iþlem dosyaya eriþemiyor: 'C:\\Users\\MONSTER\\.lazzaran\\temp\\response.mp3'
2025-01-30 07:07:32,624 - core.voice_assistant - ERROR - Error in speech recognition: 
